---
- name: Install & Configure puppet agent on slave/test node
  hosts: slave
  become: true
  tasks:
          - name: Downloading puppet agent installer repository
            get_url:
                    url: https://apt.puppetlabs.com/puppet6-release-focal.deb
                    dest: /home/jenkins_slave

          - name: Installing puppet agent repository
            shell: dpkg -i /home/jenkins_slave/puppet6-release-focal.deb

          - name: Updating apt repo & cache
            apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

          - name: Installing puppet_agent
            apt:
                    name: puppet-agent
                    state: present

          - name: Configuring puppet agent
            blockinfile:
                    dest: /etc/puppetlabs/puppet/puppet.conf
                    block: |
                            [main]
                            certname = puppetclient
                            server = puppet
          
          - name: Starting puppet agent
            systemd:
                    name: puppet
                    state: started
                    enabled: yes
